package org.alshar.lib.enums;

public enum ConstructionAlgorithm {
    MAP_CONST_RANDOM,
    MAP_CONST_IDENTITY,
    MAP_CONST_OLDGROWING,
    MAP_CONST_OLDGROWING_FASTER,
    MAP_CONST_OLDGROWING_MATRIX,
    MAP_CONST_FASTHIERARCHY_BOTTOMUP,
    MAP_CONST_FASTHIERARCHY_TOPDOWN
}
