package org.alshar.lib.enums;

public enum CycleRefinementAlgorithm {
    CYCLE_REFINEMENT_ALGORITHM_PLAYFIELD,
    CYCLE_REFINEMENT_ALGORITHM_ULTRA_MODEL,
    CYCLE_REFINEMENT_ALGORITHM_ULTRA_MODEL_PLUS
}
